# Generated by Django 5.2.6 on 2025-09-15 10:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('created', '新增'), ('updated', '修改'), ('deleted', '删除')], max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_fields', models.JSONField(blank=True, null=True)),
                ('project', models.CharField(blank=True, max_length=128, null=True)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('content', models.CharField(blank=True, max_length=1024, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '变更日志',
                'verbose_name_plural': '变更日志',
                'ordering': ['-timestamp'],
            },
        ),
    ]
