# Generated by Django 5.2.6 on 2025-12-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signals',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signals',
            name='project',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='signals',
            name='title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
