# Generated by Django 4.2.13 on 2025-05-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signals',
            name='log_content',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
