# Generated by Django 4.2.13 on 2025-05-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0003_signals_log_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signals',
            old_name='log_content',
            new_name='content',
        ),
        migrations.AddField(
            model_name='signals',
            name='project',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='signals',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
