# Generated by Django 4.2.13 on 2025-05-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0005_remove_signals_changed_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signals',
            name='changed_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
