# Generated by Django 4.2.13 on 2025-05-26 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, unique=True)),
                ('color', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, unique=True)),
            ],
            options={
                'db_table': 'task_category',
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, unique=True)),
            ],
            options={
                'db_table': 'task_status',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512)),
                ('content', models.CharField(max_length=2056, null=True)),
                ('challenge', models.CharField(max_length=2056, null=True)),
                ('feedback', models.CharField(max_length=2056, null=True)),
                ('feedback_time', models.DateTimeField(null=True)),
                ('sender', models.CharField(max_length=2056, null=True)),
                ('project', models.CharField(max_length=512, null=True)),
                ('workload', models.FloatField(default=0.0, null=True)),
                ('act_workload', models.FloatField(default=0.0, null=True)),
                ('create_time', models.DateField(null=True)),
                ('start_time', models.DateField(null=True)),
                ('done_time', models.DateField(null=True)),
                ('deadline_time', models.DateField(null=True)),
                ('progress', models.CharField(max_length=32, null=True)),
                ('description', models.CharField(max_length=512, null=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s', to='task.taskcategory')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
