# Generated by Django 4.2.13 on 2024-05-26 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='creater',
            new_name='creator',
        ),
        migrations.RemoveField(
            model_name='task',
            name='creater',
        ),
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_of_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
