# Generated by Django 4.2.13 on 2024-05-26 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0002_rename_creater_job_creator_remove_task_creater_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_of_publisher', to=settings.AUTH_USER_MODEL),
        ),
    ]
