# Generated by Django 5.2.6 on 2025-12-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_time',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='feedback',
            field=models.TextField(null=True),
        ),
    ]
