# Generated by Django 4.2.13 on 2024-07-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='workload',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
