# Generated by Django 4.2.13 on 2024-09-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_workload'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sender',
            field=models.CharField(max_length=2056, null=True),
        ),
    ]
