# Generated by Django 4.2.13 on 2024-09-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
