# Generated by Django 4.2.13 on 2024-09-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_remove_job_description_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='act_workload',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
