# Generated by Django 4.2.13 on 2024-12-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_task_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='job',
            name='granularity',
        ),
        migrations.RemoveField(
            model_name='job',
            name='group',
        ),
        migrations.RemoveField(
            model_name='job',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='job',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tags',
        ),
        migrations.AddField(
            model_name='task',
            name='feedback_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Granularity',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='JobStatus',
        ),
    ]
