# Generated by Django 4.2.19 on 2025-05-16 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='项目名')),
                ('project_type', models.CharField(default='项目', max_length=8, verbose_name='项目类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='属主')),
            ],
            options={
                'verbose_name': '项目管理',
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='ProjectEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_type', models.CharField(max_length=8, verbose_name='评价类型')),
                ('score', models.PositiveSmallIntegerField(verbose_name='评分')),
                ('comment', models.TextField(blank=True, max_length=1000, verbose_name='评语')),
                ('evaluation_time', models.DateTimeField(verbose_name='评价时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('evaluated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='被评价人')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='评价人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='project.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '项目评价',
                'db_table': 'project_evaluation',
                'indexes': [models.Index(fields=['evaluation_time', 'evaluation_type'], name='project_eva_evaluat_545ffe_idx')],
                'unique_together': {('project', 'evaluated_user', 'evaluation_time', 'evaluation_type'), ('evaluated_user', 'evaluator', 'evaluation_time', 'evaluation_type')},
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['name'], name='project_name_f50fde_idx'),
        ),
    ]
