# Generated by Django 4.2.13 on 2025-05-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='项目名')),
                ('project_type', models.CharField(default='项目', max_length=8, verbose_name='项目类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '项目管理',
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='ProjectEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255, verbose_name='项目名')),
                ('evaluation_type', models.CharField(max_length=8, verbose_name='评价类型')),
                ('score', models.PositiveSmallIntegerField(verbose_name='评分')),
                ('comment', models.TextField(blank=True, max_length=1000, verbose_name='评语')),
                ('evaluation_time', models.DateField(verbose_name='评价时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '项目评价',
                'db_table': 'project_evaluation',
            },
        ),
    ]
