# Generated by Django 5.2.6 on 2025-09-15 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='属主'),
        ),
        migrations.AddField(
            model_name='projectevaluation',
            name='evaluated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='被评价人'),
        ),
        migrations.AddField(
            model_name='projectevaluation',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='评价人'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['name'], name='project_name_f50fde_idx'),
        ),
        migrations.AddIndex(
            model_name='projectevaluation',
            index=models.Index(fields=['evaluation_time', 'evaluation_type'], name='project_eva_evaluat_545ffe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectevaluation',
            unique_together={('project', 'evaluated_user', 'evaluator', 'evaluation_time', 'evaluation_type')},
        ),
    ]
