# Generated by Django 5.2.6 on 2025-12-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='category',
            field=models.CharField(blank=True, default='测试', max_length=5),
        ),
    ]
