# Generated by Django 4.2.13 on 2024-05-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home_path',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
