# Generated by Django 5.2.6 on 2025-12-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_group_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='category',
            field=models.IntegerField(blank=True, default=1, max_length=5),
        ),
    ]
