# Generated by Django 4.2.13 on 2024-12-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='depart_leader',
            field=models.CharField(blank=True, default='', max_length=48),
        ),
        migrations.AddField(
            model_name='group',
            name='group_leader',
            field=models.CharField(blank=True, default='', max_length=48),
        ),
    ]
