# Generated by Django 4.2.13 on 2025-04-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_group_depart_leader_group_group_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='config',
            field=models.JSONField(default=dict),
        ),
    ]
